/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const apply_atome_bevy_despawn: (a: number, b: number, c: number) => void;
export const apply_atome_bevy_layer: (a: number, b: number) => void;
export const apply_atome_bevy_ops: (a: number, b: number) => void;
export const apply_atome_bevy_reparent: (a: number, b: number) => void;
export const apply_atome_bevy_resource: (a: number, b: number) => void;
export const apply_atome_bevy_scene_effects: (a: number, b: number) => void;
export const apply_atome_bevy_spawn: (a: number, b: number) => void;
export const apply_atome_bevy_style: (a: number, b: number) => void;
export const apply_atome_bevy_surface: (a: number, b: number) => void;
export const apply_atome_bevy_surface_background: (a: number, b: number) => void;
export const apply_atome_bevy_text_metadata: (a: number, b: number) => void;
export const apply_atome_bevy_transform: (a: number, b: number) => void;
export const apply_atome_bevy_visibility: (a: number, b: number) => void;
export const notify_atome_bevy_video_frame: (a: number, b: number, c: number) => void;
export const read_atome_bevy_video_backend_capabilities: (a: number) => void;
export const read_atome_bevy_video_copy_diagnostics: (a: number) => void;
export const read_atome_bevy_web_diagnostics: (a: number) => void;
export const request_atome_bevy_redraw: () => void;
export const reset_atome_bevy_video_copy_diagnostics: (a: number) => void;
export const reset_atome_bevy_web_diagnostics: (a: number) => void;
export const run_atome_bevy_preview_renderer: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const run_atome_bevy_renderer: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const __wasm_bindgen_func_elem_4932: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_4688: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_4931: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_103943: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_103927: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_4930: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_4934: (a: number, b: number, c: number, d: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
