/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const apply_atome_bevy_despawn: (a: number, b: number) => [number, number];
export const apply_atome_bevy_layer: (a: any) => [number, number];
export const apply_atome_bevy_reparent: (a: any) => [number, number];
export const apply_atome_bevy_resource: (a: any) => [number, number];
export const apply_atome_bevy_scene_effects: (a: any) => [number, number];
export const apply_atome_bevy_spawn: (a: any) => [number, number];
export const apply_atome_bevy_style: (a: any) => [number, number];
export const apply_atome_bevy_surface: (a: any) => [number, number];
export const apply_atome_bevy_surface_background: (a: any) => [number, number];
export const apply_atome_bevy_text_metadata: (a: any) => [number, number];
export const apply_atome_bevy_transform: (a: any) => [number, number];
export const apply_atome_bevy_visibility: (a: any) => [number, number];
export const notify_atome_bevy_video_frame: (a: number, b: number, c: number) => void;
export const read_atome_bevy_video_backend_capabilities: () => [number, number, number];
export const read_atome_bevy_video_copy_diagnostics: () => [number, number, number];
export const read_atome_bevy_web_diagnostics: () => [number, number, number];
export const request_atome_bevy_redraw: () => void;
export const reset_atome_bevy_video_copy_diagnostics: () => [number, number, number];
export const reset_atome_bevy_web_diagnostics: () => [number, number, number];
export const run_atome_bevy_preview_renderer: (a: number, b: number, c: number, d: number, e: any) => [number, number];
export const run_atome_bevy_renderer: (a: number, b: number, c: number, d: number, e: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h394380805492be99: (a: number, b: number, c: number) => void;
export const wasm_bindgen__closure__destroy__h0aba2fb1a3850afa: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h5ca707e6c08eb6c7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h9761e79704d05d65: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h35bfebd84f6c108c: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h0f2406f0952c411f: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h04caba32a0af2bd1: (a: number, b: number, c: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
