// Atome service worker — narrow, safe warm-load cache.
//
// It caches ONLY the Bevy renderer WASM (and its .br/.gz variants): a large asset
// that changes rarely and is content-versioned, so cache-first is both safe and a
// real warm-load win (skip re-fetching ~2.7 MB on refresh/relaunch). Everything else
// (HTML, the many frequently-changing JS modules, CSS) passes straight through to the
// network so ETag/304 keeps them fresh — no stale-JS hazard, no offline masking.
//
// The cache name embeds the renderer content version (written by the renderer build).
// A new WASM build changes the version, which changes this worker's imported version
// file, which triggers a worker update; `activate` then purges every non-current cache
// so a rebuilt WASM can never be served stale.

let RENDERER_VERSION = 'dev';
try {
    // Generated by platforms/web/bevy-renderer/build.sh next to the WASM artifact.
    self.importScripts('/wasm/renderer_version.js');
    if (typeof self.__ATOME_RENDERER_VERSION === 'string' && self.__ATOME_RENDERER_VERSION) {
        RENDERER_VERSION = self.__ATOME_RENDERER_VERSION;
    }
} catch (_) {
    // No version file (unbuilt / non-web runtime): fall back to a fixed name; still functional.
}

const CACHE_NAME = `atome-wasm-${RENDERER_VERSION}`;
const WASM_PATH_RE = /\/wasm\/squirrel_bevy_renderer_bg\.wasm(\.br|\.gz)?$/;

const isCacheableWasm = (request) => {
    if (request.method !== 'GET') return false;
    let url;
    try { url = new URL(request.url); } catch (_) { return false; }
    return url.origin === self.location.origin && WASM_PATH_RE.test(url.pathname);
};

self.addEventListener('install', (event) => {
    // Take over as soon as the new worker is ready instead of waiting for all tabs to close.
    event.waitUntil(self.skipWaiting());
});

self.addEventListener('activate', (event) => {
    event.waitUntil((async () => {
        const names = await caches.keys();
        await Promise.all(names
            .filter((name) => name.startsWith('atome-wasm-') && name !== CACHE_NAME)
            .map((name) => caches.delete(name)));
        await self.clients.claim();
    })());
});

self.addEventListener('fetch', (event) => {
    if (!isCacheableWasm(event.request)) return; // passthrough: default network handling
    event.respondWith((async () => {
        const cache = await caches.open(CACHE_NAME);
        const cached = await cache.match(event.request);
        if (cached) return cached;
        const response = await fetch(event.request);
        // Only cache complete, successful responses (skip 206/opaque/errors).
        if (response && response.status === 200 && response.type === 'basic') {
            cache.put(event.request, response.clone());
        }
        return response;
    })());
});
