# overlays/network/wpa_supplicant.conf
# Template par défaut. L'utilisateur ajoutera ses réseaux via
# le service atome (ou au premier boot, pré-configuration possible).

ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=wheel
update_config=1

# Exemple (commenté) :
# network={
#     ssid="MonWifi"
#     psk="motdepasse"
#     key_mgmt=WPA-PSK
# }

# Réseaux ouverts en dernier recours
network={
    key_mgmt=NONE
    priority=0
    disabled=1
}
