import assert from 'node:assert/strict';
import { installMockBrowserEnv } from '../strangler_v2/_env.mjs';
const {document,window}=installMockBrowserEnv();
const {publishBevySurfaceBackground,readResolvedBevySurfaceBackgroundMedia}=await import('../../eVe/domains/rendering/bevy_surface_background_runtime.js');
const rgba=new Uint8Array([20,40,60,255]);
publishBevySurfaceBackground({signature:'login-shared-generated',mode:'generated',fit:'cover',color:[0,0,0,1],texture:{width:1,height:1,rgba}},window);
const media=await readResolvedBevySurfaceBackgroundMedia(document.createElement('canvas'));
assert.equal(media.texture.rgba,rgba,'login must reuse canonical texture bytes without a second decode/source');
assert.equal(media.signature,'login-shared-generated');
console.log('login canonical wallpaper reuse: ok');

const {createVirtualSceneTree,diffVirtualSceneTrees}=await import('../../eVe/domains/rendering/virtual_scene_contract.js');
const shape={id:'workspace_shape',type:'shape',properties:{left:0,top:0,width:100,height:100,color:'#ff0000'}};
const canonical=createVirtualSceneTree([shape]);
const overlay=createVirtualSceneTree([{...shape,properties:{...shape.properties,presentation:true}}]);
const restoreOps=diffVirtualSceneTrees(overlay,canonical);
assert.ok(restoreOps.some(op=>op.type==='despawn'&&op.id==='workspace_shape'));
assert.ok(restoreOps.some(op=>op.type==='spawn'&&op.node.id==='workspace_shape'&&op.node.presentation===false));
console.log('login handoff restores workspace capture membership: ok');

const {registerBevySurfaceBackgroundRuntime,ensureBevySurfaceBackgroundApplied}=await import('../../eVe/domains/rendering/bevy_surface_background_runtime.js');
let applications=[];
const surface=document.createElement('canvas');
registerBevySurfaceBackgroundRuntime(surface,{started:true,wasmModule:{apply_atome_bevy_surface_background:payload=>applications.push(payload),request_atome_bevy_redraw:()=>{}}});
assert.equal(await ensureBevySurfaceBackgroundApplied(surface),true);
assert.equal(applications.at(-1).texture.rgba,rgba);
const count=applications.length;
assert.equal(await ensureBevySurfaceBackgroundApplied(surface),true);
assert.equal(applications.length,count,'unchanged wallpaper must not be uploaded again during an animation');
console.log('login waits for canonical background without repeated uploads: ok');
