import assert from 'node:assert/strict';
import { installMockBrowserEnv } from '../strangler_v2/_env.mjs';
const {document,window}=installMockBrowserEnv();
const {setLoginCanvasPresentation,loginCanvasHost,loginPresentationRecords}=await import('../../eVe/domains/rendering/login_canvas_presentation.js');
const host=document.createElement('div'), project=document.createElement('div');
const records=[{id:'canonical_project_object'}], login=[{id:'login_pixels'}];
let events=0;window.addEventListener('eve:login-canvas-presentation',()=>events++);
const state={host,records:login,returnHost:null};setLoginCanvasPresentation(state);
assert.equal(loginCanvasHost(project,document),host);
assert.equal(state.returnHost,project);
assert.equal(loginPresentationRecords(records),login);
assert.deepEqual(records,[{id:'canonical_project_object'}]);
state.revealWorkspace=true;
state.workspaceBackground=[245/255,245/255,247/255,1];
const revealed=loginPresentationRecords(records);
assert.equal(revealed[0].properties.renderLayer,-1);
assert.equal(revealed[1].id,records[0].id);
assert.equal(revealed[1].properties.opacity,1);
assert.equal(revealed[1].properties.presentation,true);
assert.equal(revealed[1].properties.renderLayer,1360);
state.workspaceOpacity=.25;
assert.equal(loginPresentationRecords(records)[1].properties.opacity,.25);
assert.deepEqual(records,[{id:'canonical_project_object'}]);
assert.equal(revealed[2],login[0]);
assert.equal(records.length,1);
const foreignDocument={};assert.equal(loginCanvasHost(project,foreignDocument),project);
setLoginCanvasPresentation(null);
assert.equal(loginCanvasHost(project,document),project);
assert.equal(loginPresentationRecords(records),records);
assert.equal(events,2);
console.log('login canvas presentation ownership: ok');

const {publishBevySurfaceBackground,readResolvedBevySurfaceBackgroundMedia}=await import('../../eVe/domains/rendering/bevy_surface_background_runtime.js');
const rgba=new Uint8Array([20,40,60,255]);
publishBevySurfaceBackground({signature:'login-shared-generated',mode:'generated',fit:'cover',color:[0,0,0,1],texture:{width:1,height:1,rgba}},window);
const media=await readResolvedBevySurfaceBackgroundMedia(document.createElement('canvas'));
assert.equal(media.texture.rgba,rgba,'login must reuse canonical texture bytes without a second decode/source');
assert.equal(media.signature,'login-shared-generated');
console.log('login canonical wallpaper reuse: ok');

const {createVirtualSceneTree,diffVirtualSceneTrees}=await import('../../eVe/domains/rendering/virtual_scene_contract.js');
const shape={id:'workspace_shape',type:'shape',properties:{left:0,top:0,width:100,height:100,color:'#ff0000'}};
const canonical=createVirtualSceneTree([shape]);
const overlay=createVirtualSceneTree([{...shape,properties:{...shape.properties,presentation:true}}]);
const restoreOps=diffVirtualSceneTrees(overlay,canonical);
assert.ok(restoreOps.some(op=>op.type==='despawn'&&op.id==='workspace_shape'));
assert.ok(restoreOps.some(op=>op.type==='spawn'&&op.node.id==='workspace_shape'&&op.node.presentation===false));
console.log('login handoff restores workspace capture membership: ok');

const {registerBevySurfaceBackgroundRuntime,ensureBevySurfaceBackgroundApplied}=await import('../../eVe/domains/rendering/bevy_surface_background_runtime.js');
let applications=[];
const surface=document.createElement('canvas');
registerBevySurfaceBackgroundRuntime(surface,{started:true,wasmModule:{apply_atome_bevy_surface_background:payload=>applications.push(payload),request_atome_bevy_redraw:()=>{}}});
assert.equal(await ensureBevySurfaceBackgroundApplied(surface),true);
assert.equal(applications.at(-1).texture.rgba,rgba);
const count=applications.length;
assert.equal(await ensureBevySurfaceBackgroundApplied(surface),true);
assert.equal(applications.length,count,'unchanged wallpaper must not be uploaded again during an animation');
console.log('login waits for canonical background without repeated uploads: ok');

const {blurCanvasImage}=await import('../../eVe/intuition/tools/user_login_canvas_blur.js');
const input=new Uint8ClampedArray(9*9*4);input[(4*9+4)*4]=255;input[(4*9+4)*4+3]=255;
let filtered;
blurCanvasImage({width:9,height:9,getContext:()=>({getImageData:()=>({data:input}),putImageData:data=>{filtered=data.data}})},1);
assert.ok(filtered[(4*9+4)*4+3]>0&&filtered[(4*9+4)*4+3]<255);
assert.ok(filtered[(4*9+3)*4+3]>0);
for(let i=0;i<filtered.length;i+=4)if(filtered[i+3])assert.equal(filtered[i],255,'blur must preserve the SVG colour at transparent edges');
console.log('portable logo blur preserves source colour: ok');
